add LibPspExploit
pspdev/psp-packages pull request #109
Opened 2024-02-10 21:20 UTC by bucanero

2024-02-10 21:37 UTC, bucanero commented on libpspexploit/PSPBUILD
> +license=('Unknown')
```suggestion
license=('WTFPL')
```

2024-02-11 00:30 UTC, diamant3 requested changes
thanks! @bucanero but could you add the license to package too

2024-02-11 01:25 UTC, bucanero commented
> thanks! @bucanero but could you add the license to package too

license added 👍

2024-02-11 02:18 UTC, diamant3 reviewed
After that, I will merge it

2024-02-11 02:18 UTC, diamant3 commented on libpspexploit/PSPBUILD
> +    cp COPYING "${srcdir}/LibPspExploit-${pkgver}/LICENSE"
and then this one, you could rename the LICENSE.txt from the source to LICENSE

2024-02-11 11:19 UTC, merged

2024-02-11 11:20 UTC, diamant3 commented
Thanks!