add pspuart package
pspdev/psp-packages pull request #144
Opened 2024-05-30 09:59 UTC by tpimh

2024-05-30 14:18 UTC, sharkwouter requested changes
Thanks for making this PR, always cool to see new libraries. I did find an issue with the license, otherwise this package looks good.

2024-05-30 14:18 UTC, sharkwouter commented on pspuart/PSPBUILD
> +license=('cc-by-sa-3.0')
This does not match the bundled license, it should be cc-by-sa-4.0.

2024-05-31 07:29 UTC, tpimh commented
Oops, I tried to use commit hash as pkgver and epoch to increment on every change, but it seems that files with colon in their name can't be uploaded as artifacts.

2024-05-31 07:57 UTC, sharkwouter commented
That's odd, that means we cannot use epoch.

2024-05-31 08:03 UTC, tpimh commented
There must be a workaround, I'll check. Using it makes sense with packages with no version.

2024-05-31 08:13 UTC, sharkwouter commented
You could copy the pkgver function from libpspvram. That takes the commit number and the sha hash to create the version number.

2024-06-02 11:43 UTC, tpimh commented
I wonder if it should be called pspuart or libpspuart... Since all the packages are libraries, "lib" prefix seems redundant.

2024-06-02 13:10 UTC, merged

2024-06-02 13:11 UTC, sharkwouter commented
Yeah, lib in front of the package name is kinda useless for most packages. Some have it explicitly in their publicly known name.

Thanks for this update, I've merged it.