SDL updates
pspdev/psp-packages pull request #145
Opened 2024-05-30 11:40 UTC by tpimh

*This is just a draft for now, I will add more info below.*

List of SDL 1.2 packages:

- sdl
- sdl_gfx
- sdl_image
- sdl_mixer
- sdl_net (added by this PR)
- sdl_ttf

List of SDL 2.0 packages:

- sdl2
- sdl2_gfx
- sdl2_image
- sdl2_mixer
- sdl2_net (added by this PR)
- sdl2_ttf

2024-05-30 14:24 UTC, sharkwouter commented
With some of the license changes we have to be really careful here. If a library links to anything that has a different license, that can affect the licensing of the package. We should probably bundle the licenses of dependencies in the licenses directory of a package to be honest.

2024-05-30 18:10 UTC, tpimh commented
I believe the licenses of these libraries were not changed, they were just indicated incorrectly. Anyway, Zlib is a very permissive license, and very similar to MIT, so this change shouldn't affect anything, and `GPL2.1` doesn't exist, it's just a typo.

2024-05-30 19:31 UTC, sharkwouter requested changes
There were still some pkgrel increases missing. Otherwise this looks good to me. I'll comment to explain the logic behind the weird licenses, but I'm okay with changing them with the PR.

2024-05-30 19:31 UTC, sharkwouter commented on sdl-mixer/PSPBUILD
>  pkgrel=4
pkgrel should be increased

2024-05-30 19:36 UTC, sharkwouter commented
> I believe the licenses of these libraries were not changed, they were just indicated incorrectly. Anyway, Zlib is a very permissive license, and very similar to MIT, so this change shouldn't affect anything, and `GPL2.1` doesn't exist, it's just a typo.

What I meant was that because we can only build static binaries for the PSP, I set the license of the SDL packages to the one of the least permissive dependency, because it communicates to the developer using the library what rules they have to apply to. That might also be why I removed the L from LGPL, because when you statically linking, you are bound by the GPL when using LGPL licensed libraries.

I do think it makes sense to change this to the actual license of the library, but I don't know what other way we could use to communicate what license limitations your program will have to abide by when using a library.

2024-05-31 04:42 UTC, tpimh commented
Yes, static linking is one of the pitfalls of GPL. But I believe there's a workaround for it: instead of linking statically, GPL modules can be built as PRXs and loaded dynamically (that requires some patching though). Also it makes sense to introduce flags (like in gentoo) to build packages with different optional dependencies.

2024-05-31 04:53 UTC, tpimh commented
Also, the there's a problem with SDL 1.2 versions: they stopped adding new functions and creating new releases (version is frozen), but the code is still updated with fixes for new compilers and occasional backports from SDL2.

I can see several solutions there:

1. Use the last release version as `pkgver`, keep increasing `pkgrel` (problem with sdl_image and sdl_mixer as the version will go down)
2. Use the version indicated in changelog as `pkgver`, keep increasing `pkgrel` (problem only with sdl_mixer as the version will go down)
3. Use commit hash as `pkgver`, and start incrementing `epoch` every time it changes (version number doesn't make any sense anymore)

2024-05-31 08:04 UTC, tpimh commented
I guess I should just skip checksum verification for all local files.

2024-05-31 08:27 UTC, sharkwouter commented
I would just use the latest available version number for the package of SDL 1.2. That should be fine since they will not release new versions anyway.

2024-05-31 08:45 UTC, tpimh commented
Makes sense, but then version numbers will decrement for two packages (possible problem for updates).

2024-05-31 10:05 UTC, sharkwouter commented
> Makes sense, but then version numbers will decrement for two packages (possible problem for updates).

I think that's acceptable to do once.

2024-06-03 12:51 UTC, sharkwouter commented
@tpimh could you still increase the pkgrel of the packages where that hasn't been done yet? Then we can get this merged, since it otherwise looks great. I just did a fix in SDL2 upstream which fixes SDL2main and I'd like to add that after merging this PR. Thanks in advance, I do really appreciate your work on this.

2024-06-03 12:56 UTC, tpimh commented
I was thinking of actually updating every SDL package to the latest version, but I guess just bumping pkgrel is fine.

2024-06-03 13:22 UTC, merged

2024-06-03 13:23 UTC, sharkwouter commented
Thanks! I appreciate the quick response. Updating can still be done in another PR.