Add Eigen3
pspdev/psp-packages pull request #58
Opened 2022-10-22 17:00 UTC by KorigamiK

Eigen3 is an awesome C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.

It is fully inline so there should not be any static or shared libraries required to link.

I would love to know how you would go about linking this one in a cmakelists.txt :D

2022-10-22 19:46 UTC, KorigamiK commented
I've created a [minimal working example](https://gist.github.com/KorigamiK/97fb9536ce9ae29aff29f7d719483f29) to test that it works :)

2022-10-23 15:36 UTC, sharkwouter commented
Thanks! I'll give this a test and do a review.

2022-10-23 16:10 UTC, sharkwouter requested changes
At the moment I can't accept this yet, because the generated package is empty. I made 2 suggestions which should resolve that.

You might also want to make sure the pkgconfig file revers to $PSPDEV in a similar fashion the SDL packages does it: https://github.com/pspdev/psp-packages/blob/9e1eb362ac8ef95688349c23f11baa0f8f8acc05/sdl2/PSPBUILD#L17

Other than that this looks good. Thanks for the PR, it's good to see other people make some.

2022-10-23 17:17 UTC, KorigamiK commented on eigen3/PSPBUILD
> +  cmake .. -DCMAKE_TOOLCHAIN_FILE="$PSPDEV/psp/share/pspdev.cmake" -DCMAKE_INSTALL_PREFIX="$PSPDEV/psp" -DCMAKE_BUILD_TYPE=Release -Wno-dev -DBUILD_SHARED_LIBS=OFF
Aah, if I understand correctly, the `/psp` directory will automatically be installed to `$PSPDEV/psp`. Is that right?

As of now I can see that the Library is actually installed and the files are saved in the correct location.

2022-10-23 19:05 UTC, sharkwouter commented on eigen3/PSPBUILD
> +  cmake .. -DCMAKE_TOOLCHAIN_FILE="$PSPDEV/psp/share/pspdev.cmake" -DCMAKE_INSTALL_PREFIX="$PSPDEV/psp" -DCMAKE_BUILD_TYPE=Release -Wno-dev -DBUILD_SHARED_LIBS=OFF
Exactly :D

2022-10-25 15:47 UTC, KorigamiK commented
Thanks for the changes, I can't test them at the moment but please change them as you desire.

2022-10-25 18:30 UTC, merged